kind: Namespace
apiVersion: v1
metadata:
  name: svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
  namespace: svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tcp-server
      app.kubernetes.io/instance: tcp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tcp-server
        app.kubernetes.io/instance: tcp-server
    spec:
      serviceAccountName: tcp-server
      securityContext:
        {}
      containers:
        - name: tcp-server
          securityContext:
            {}
          image: "${TCPSERVER_IMAGE_REPO_URL}:${BUILDRUN_HASH}"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -XX:+HeapDumpOnOutOfMemoryError
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_HOST
              value: "${DB_HOST}"
            - name: DB_USER
              value: "root"
            - name: OCI_STREAM_MESSAGING_ENDPOINT
              value: "${STREAM_MESSAGING_ENDPOINT}"
            - name: OCI_STREAM_OCID
              value: "${STREAM_OCID}"
            - name: OCI_AUTH_PROFILE
              value: "${AUTH_PROFILE}"
            - name: OCI_TENANT
              value: "<tn_ph>"
            - name: OCI_USER_ID
              value: "<user_ph>"
            - name: OCI_USER_FINGER_PRINT
              value: "<fp_ph>"
            - name: OCI_PVT_KEY_PATH
              value: "<path_ph>"
            - name: TCP_SERVER_PORT
              value: "${TCP_SERVER_PORT}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tcp-server-secret
                  key: db-password
          livenessProbe:
            tcpSocket:
              port: ${TCP_SERVER_PORT}
            initialDelaySeconds: 90
            periodSeconds: 2
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: ${TCP_SERVER_PORT}
            initialDelaySeconds: 60
            periodSeconds: 2
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          ports:
            - name: tcp
              containerPort: ${TCP_SERVER_PORT}
              protocol: TCP
          resources:
            limits:
              cpu: 6500m
              memory: 8192Mi
            requests:
              cpu: 4500m
              memory: 6144Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server
  namespace: svc
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/backend-policy: "FIVE_TUPLE"
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
spec:
  type: LoadBalancer
  ports:
    - port: ${TCP_SERVER_PORT}
      protocol: TCP
      name: tcp
      targetPort: ${TCP_SERVER_PORT}
  selector:
    app.kubernetes.io/name: tcp-server
    app.kubernetes.io/instance: tcp-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tcp-server
  namespace: svc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tcp-server-hpa
  namespace: svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tcp-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50