kind: Namespace
apiVersion: v1
metadata:
  name: svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
      app.kubernetes.io/instance: notification-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notification-service
        app.kubernetes.io/instance: notification-service
    spec:
      serviceAccountName: notification-service
      securityContext:
        {}
      containers:
        - name: notification-service
          securityContext:
            {}
          image: "${NOTIFICATION_IMAGE_REPO_URL}:${BUILDRUN_HASH}"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -XX:+HeapDumpOnOutOfMemoryError
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_HOST
              value: "${DB_HOST}"
            - name: DB_USER
              value: "root"
            - name: OCI_QUEUE_OCID
              value: "${QUEUE_OCID}"
            - name: OCI_QUEUE_REGION_ID
              value: "${QUEUE_REGION_ID}"
            - name: OCI_AUTH_PROFILE
              value: "${AUTH_PROFILE}"
            - name: OCI_SMTP_USERNAME
              value: "${SMTP_USERNAME}"
            - name: OCI_SMTP_PASSWORD_OCID
              value: "${SMTP_PASSWORD_OCID}"
            - name: OCI_EMAIL_HOST
              value: "${EMAIL_HOST}"
            - name: OCI_EMAIL_PORT
              value: "587"
            - name: OCI_EMAIL_FROM_ADDRESS
              value: "${EMAIL_FROM_ADDRESS}"
            - name: OCI_EMAIL_FROM_NAME
              value: "OCI IoT Sample Health App"
            - name: OCI_EMAIL_SUBJECT
              value: "Warning! Abnormal Health Reading observed"
            - name: OCI_TENANT
              value: "<tn_ph>"
            - name: OCI_USER_ID
              value: "<user_ph>"
            - name: OCI_USER_FINGER_PRINT
              value: "<fp_ph>"
            - name: OCI_PVT_KEY_PATH
              value: "<path_ph>"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: db-password
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 1024Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: svc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50